export const products = [
    {
      id: 1,
      name: "Wireless Mouse",
      price: 25.99,
      category: "Electronics",
      description: "A comfortable and reliable wireless mouse.",
      stock: 100,
      rating: 4.5,
      imageUrl: "https://example.com/images/wireless-mouse.jpg",
    },
    {
      id: 2,
      name: "Bluetooth Headphones",
      price: 59.99,
      category: "Electronics",
      description: "Noise-cancelling over-ear Bluetooth headphones.",
      stock: 50,
      rating: 4.7,
      imageUrl: "https://example.com/images/bluetooth-headphones.jpg",
    },
    {
      id: 3,
      name: "Running Shoes",
      price: 79.99,
      category: "Sportswear",
      description: "Lightweight and durable running shoes for all terrains.",
      stock: 200,
      rating: 4.3,
      imageUrl: "https://example.com/images/running-shoes.jpg",
    },
    {
      id: 4,
      name: "Smartphone",
      price: 499.99,
      category: "Electronics",
      description: "A fast and powerful smartphone with a stunning display.",
      stock: 30,
      rating: 4.8,
      imageUrl: "https://example.com/images/smartphone.jpg",
    },
    {
      id: 5,
      name: "Office Chair",
      price: 149.99,
      category: "Furniture",
      description: "Ergonomic office chair with lumbar support.",
      stock: 75,
      rating: 4.6,
      imageUrl: "https://example.com/images/office-chair.jpg",
    },
  ];